services:
  # FastAPI Backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - FRONTEND_URL=http://192.168.2.88.nip.io
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: /api
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
