-- Migration 012: Add status_token to queue_items for unique customer status links.
--
-- Each queue item receives a cryptographically random token when a customer joins.
-- The token is used to build a public URL:
--   https://zeroqwait.com/queue-status/{token}
-- that the customer can visit without logging in to see their live position.
--
-- Token is generated by the backend (secrets.token_urlsafe(32)) and is never
-- predictable or reused. It is stored NULL for items that joined before this
-- migration.

ALTER TABLE queue_items
    ADD COLUMN IF NOT EXISTS status_token VARCHAR(64) UNIQUE;

CREATE INDEX IF NOT EXISTS idx_queue_items_status_token
    ON queue_items (status_token)
    WHERE status_token IS NOT NULL;
