apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-service
  namespace: zeroqwait
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr-service
  template:
    metadata:
      labels:
        app: asr-service
    spec:
      priorityClassName: voice-critical
      containers:
        - name: asr-service
          image: localhost:5000/test/asr-service:v20260411223946-c5f88d4
          imagePullPolicy: Always
          env:
            - name: MODEL_SIZE
              value: "medium"
            - name: DEVICE
              value: "cpu"
            - name: COMPUTE_TYPE
              value: "int8"
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
