apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeroqwait-docs-ingress
  namespace: zeroqwait
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - "192.168.2.88.nip.io"
    - "*.192.168.2.88.nip.io"
    - "zeroqwait.com"
    - "*.zeroqwait.com"
    secretName: zeroqwait-wildcard-tls
  rules:
  - host: "192.168.2.88.nip.io"
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
  - host: "*.192.168.2.88.nip.io"
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
  - host: "zeroqwait.com"
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
  - host: "*.zeroqwait.com"
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
