apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: zeroqwait
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      priorityClassName: app-standard
      tolerations:
      - key: "workload-pool"
        operator: "Equal"
        value: "edge-cpu"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: zeroqwait.io/node-pool
                operator: In
                values: ["edge-cpu"]
      containers:
      - name: frontend
        image: localhost:5000/prod/frontend:v20260505055008-8e862e4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      # Since this is a "deployment" pipeline, we assume immutable images.
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: zeroqwait
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 80
    nodePort: 30001

