apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: zeroqwait
type: Opaque
stringData:
  POSTGRES_USER: fastcuts_user
  POSTGRES_PASSWORD: fastcuts_secure_password_change_in_production
  POSTGRES_DB: fastcuts_db
