import React, { useCallback, useEffect, useMemo } from "react";
import {
  Alert,
  alpha,
  Box,
  ButtonBase,
  Chip,
  CircularProgress,
  Stack,
  Typography,
  useTheme,
} from "@mui/material";
import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded";
import ChecklistRoundedIcon from "@mui/icons-material/ChecklistRounded";
import RadioButtonUncheckedRoundedIcon from "@mui/icons-material/RadioButtonUncheckedRounded";
import {
  useAssistantInteractable,
  useInteractableState,
} from "@assistant-ui/react";

export type AgentTaskBoardTask = {
  id: string;
  title: string;
  description: string;
  done: boolean;
  source: "manual" | "approval" | "agent";
  assignee?: string;
  createdAt: string;
  actionId?: string;
  detailLines?: string[];
};

export type AgentTaskBoardState = {
  tasks: AgentTaskBoardTask[];
};

export type AgentTaskBoardExternalTask = Omit<AgentTaskBoardTask, "done"> & {
  done?: boolean;
};

interface AgentTaskBoardProps {
  interactableId: string;
  externalTasks?: AgentTaskBoardExternalTask[];
}

const TASK_BOARD_STATE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["tasks"],
  properties: {
    tasks: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "title", "description", "done", "source", "createdAt"],
        properties: {
          id: { type: "string" },
          title: { type: "string" },
          description: { type: "string" },
          done: { type: "boolean" },
          source: {
            type: "string",
            enum: ["manual", "approval", "agent"],
          },
          assignee: { type: "string" },
          createdAt: { type: "string" },
          actionId: { type: "string" },
          detailLines: {
            type: "array",
            items: { type: "string" },
          },
        },
      },
    },
  },
} as const;

const TASK_BOARD_INITIAL_STATE: AgentTaskBoardState = {
  tasks: [],
};

const sortTasks = (tasks: AgentTaskBoardTask[]) =>
  [...tasks].sort((left, right) => {
    if (left.done !== right.done) {
      return left.done ? 1 : -1;
    }

    return new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime();
  });

const areTasksEqual = (left: AgentTaskBoardTask, right: AgentTaskBoardTask) =>
  left.id === right.id &&
  left.title === right.title &&
  left.description === right.description &&
  left.done === right.done &&
  left.source === right.source &&
  left.assignee === right.assignee &&
  left.createdAt === right.createdAt &&
  left.actionId === right.actionId &&
  (left.detailLines || []).join("\n") === (right.detailLines || []).join("\n");

const normalizeExternalTask = (
  task: AgentTaskBoardExternalTask,
  existing?: AgentTaskBoardTask,
): AgentTaskBoardTask => ({
  id: task.id,
  title: task.title,
  description: task.description,
  done: existing?.done ?? task.done ?? false,
  source: task.source,
  assignee: task.assignee,
  createdAt: task.createdAt,
  actionId: task.actionId,
  detailLines: task.detailLines,
});

const AgentTaskBoard: React.FC<AgentTaskBoardProps> = ({
  interactableId,
  externalTasks = [],
}) => {
  const theme = useTheme();

  const registeredId = useAssistantInteractable("taskBoard", {
    id: interactableId,
    description:
      "A persistent owner task board for manual follow-ups, employee tasks, and approval work generated by the agent workspace.",
    stateSchema: TASK_BOARD_STATE_SCHEMA,
    initialState: TASK_BOARD_INITIAL_STATE,
  });

  const [state, { setState, setSelected, isPending, error }] =
    useInteractableState<AgentTaskBoardState>(registeredId, TASK_BOARD_INITIAL_STATE);

  useEffect(() => {
    if (externalTasks.length === 0) {
      return;
    }

    setState((prev: AgentTaskBoardState) => {
      const existingTasks = prev.tasks || [];
      const taskMap = new Map<string, AgentTaskBoardTask>(
        existingTasks.map((task) => [task.id, task]),
      );
      let changed = false;

      externalTasks.forEach((task) => {
        const current = taskMap.get(task.id);
        const next = normalizeExternalTask(task, current);

        if (!current || !areTasksEqual(current, next)) {
          taskMap.set(next.id, next);
          changed = true;
        }
      });

      if (!changed) {
        return prev;
      }

      const nextTasks = sortTasks(Array.from(taskMap.values()));
      if (
        nextTasks.length === existingTasks.length &&
        nextTasks.every((task, index) => areTasksEqual(task, existingTasks[index]!))
      ) {
        return prev;
      }

      return { tasks: nextTasks };
    });
  }, [externalTasks, setState]);

  const tasks = useMemo(() => sortTasks(state.tasks || []), [state.tasks]);
  const doneCount = tasks.filter((task) => task.done).length;

  const handleToggleTask = useCallback(
    (taskId: string) => {
      setSelected(true);
      setState((prev: AgentTaskBoardState) => ({
        tasks: sortTasks(
          (prev.tasks || []).map((task: AgentTaskBoardTask) =>
            task.id === taskId ? { ...task, done: !task.done } : task,
          ),
        ),
      }));
    },
    [setSelected, setState],
  );

  return (
    <Box
      onClick={() => setSelected(true)}
      sx={{
        width: "100%",
        height: "100%",
        minHeight: { xs: 320, md: 0 },
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
        borderLeft: "1px solid",
        borderColor: "divider",
        backgroundColor:
          theme.palette.mode === "dark"
            ? alpha(theme.palette.common.white, 0.02)
            : alpha(theme.palette.text.primary, 0.02),
      }}
    >
      <Stack
        alignItems="center"
        direction="row"
        spacing={1}
        sx={{ px: 1.25, pt: 0, pb: 0, borderBottom: "1px solid", borderColor: "divider" }}
      >
        <Stack direction="row" alignItems="center" spacing={1} sx={{ minWidth: 0, flex: 1 }}>
          <ChecklistRoundedIcon sx={{ fontSize: 18, color: "text.secondary" }} />
          <Typography variant="subtitle2" sx={{ fontWeight: 600 }}>
            Task Board
          </Typography>
        </Stack>

        {isPending ? <CircularProgress size={12} sx={{ color: "text.secondary" }} /> : null}

        {tasks.length > 0 ? (
          <Box
            sx={{
              ml: "auto",
              borderRadius: 999,
              px: 1,
              py: 0.25,
              fontSize: 12,
              fontWeight: 600,
              color: "primary.main",
              backgroundColor: alpha(theme.palette.primary.main, 0.1),
            }}
          >
            {doneCount}/{tasks.length}
          </Box>
        ) : null}
      </Stack>

      <Box sx={{ flex: 1, minHeight: 0, overflowY: "auto", px: 0, pt: 0, pb: 0 }}>
        {error ? (
          <Alert severity="error" sx={{ mb: 1.5 }}>
            Failed to sync task board state.
          </Alert>
        ) : null}

        {tasks.length === 0 ? (
          <Stack
            spacing={0.5}
            alignItems="center"
            justifyContent="center"
            sx={{
              minHeight: "100%",
              color: "text.secondary",
              textAlign: "center",
              px: 2,
            }}
          >
            <ChecklistRoundedIcon
              sx={{
                mb: 0.5,
                fontSize: 32,
                color: alpha(theme.palette.text.secondary, 0.3),
              }}
            />
            <Typography variant="body2" sx={{ fontWeight: 500, color: "text.secondary" }}>
              No tasks yet.
            </Typography>
            <Typography
              variant="caption"
              sx={{ color: alpha(theme.palette.text.secondary, 0.8) }}
            >
              Ask the assistant to add some!
            </Typography>
          </Stack>
        ) : (
          <Box component="ul" sx={{ m: 0, p: 0, listStyle: "none" }}>
            {tasks.map((task) => (
              <Box component="li" key={task.id}>
                <ButtonBase
                  onClick={() => handleToggleTask(task.id)}
                  sx={{
                    display: "flex",
                    width: "100%",
                    justifyContent: "flex-start",
                    alignItems: "flex-start",
                    gap: 1.25,
                    borderRadius: 0,
                    px: 0.75,
                    py: 1,
                    minHeight: task.source === "approval" ? 82 : 44,
                    textAlign: "left",
                    opacity: task.done ? 0.56 : 1,
                    transition: theme.transitions.create(["background-color", "opacity"], {
                      duration: theme.transitions.duration.shorter,
                    }),
                    "&:hover": {
                      backgroundColor:
                        theme.palette.mode === "dark"
                          ? alpha(theme.palette.common.white, 0.04)
                          : alpha(theme.palette.text.primary, 0.04),
                    },
                  }}
                  title={task.description || task.title}
                >
                  {task.done ? (
                    <CheckCircleRoundedIcon sx={{ mt: 0.25, fontSize: 18, color: "primary.main", flexShrink: 0 }} />
                  ) : (
                    <RadioButtonUncheckedRoundedIcon
                      sx={{ mt: 0.25, fontSize: 18, color: "text.secondary", flexShrink: 0 }}
                    />
                  )}

                  <Stack spacing={0.5} sx={{ flex: 1, minWidth: 0 }}>
                    <Stack direction="row" spacing={0.75} alignItems="center" sx={{ minWidth: 0 }}>
                      <Typography
                        variant="body2"
                        sx={{
                          flex: 1,
                          minWidth: 0,
                          fontWeight: 600,
                          color: task.done ? "text.secondary" : "text.primary",
                          textDecoration: task.done ? "line-through" : "none",
                          wordBreak: "break-word",
                        }}
                      >
                        {task.title}
                      </Typography>

                      {task.source === "approval" ? (
                        <Chip
                          size="small"
                          label="Approve"
                          sx={{
                            height: 20,
                            fontSize: 11,
                            fontWeight: 700,
                            color: "primary.main",
                            backgroundColor: alpha(theme.palette.primary.main, 0.1),
                          }}
                        />
                      ) : null}
                    </Stack>

                    {task.description ? (
                      <Typography
                        variant="caption"
                        sx={{
                          color: alpha(theme.palette.text.secondary, 0.92),
                          display: "-webkit-box",
                          WebkitLineClamp: 2,
                          WebkitBoxOrient: "vertical",
                          overflow: "hidden",
                          lineHeight: 1.35,
                        }}
                      >
                        {task.description}
                      </Typography>
                    ) : null}

                    {task.detailLines && task.detailLines.length > 0 ? (
                      <Stack direction="row" spacing={0.5} useFlexGap flexWrap="wrap">
                        {task.detailLines.slice(0, 3).map((detail) => (
                          <Chip
                            key={detail}
                            size="small"
                            label={detail}
                            sx={{
                              height: 20,
                              maxWidth: "100%",
                              fontSize: 11,
                              color: "text.secondary",
                              backgroundColor:
                                theme.palette.mode === "dark"
                                  ? alpha(theme.palette.common.white, 0.05)
                                  : alpha(theme.palette.text.primary, 0.05),
                            }}
                          />
                        ))}
                      </Stack>
                    ) : null}
                  </Stack>
                </ButtonBase>
              </Box>
            ))}
          </Box>
        )}
      </Box>
    </Box>
  );
};

export default AgentTaskBoard;
