import React, { useCallback, useEffect, useMemo } from "react";
import { CheckCircle2, Circle, ClipboardList } from "lucide-react";
import {
  useAssistantInteractable,
  useInteractableState,
} from "@assistant-ui/react";
import type { JSONSchema7 } from "json-schema";
import { cn } from "../../lib/utils";

export type AgentTaskBoardTask = {
  id: string;
  title: string;
  description: string;
  done: boolean;
  source: "manual" | "approval" | "agent";
  assignee?: string;
  createdAt: string;
  actionId?: string;
};

export type AgentTaskBoardState = {
  tasks: AgentTaskBoardTask[];
};

export type AgentTaskBoardExternalTask = Omit<AgentTaskBoardTask, "done"> & {
  done?: boolean;
};

interface AgentTaskBoardProps {
  interactableId: string;
  externalTasks?: AgentTaskBoardExternalTask[];
}

const TASK_BOARD_STATE_SCHEMA: JSONSchema7 = {
  type: "object",
  additionalProperties: false,
  required: ["tasks"],
  properties: {
    tasks: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "title", "description", "done", "source", "createdAt"],
        properties: {
          id: { type: "string" },
          title: { type: "string" },
          description: { type: "string" },
          done: { type: "boolean" },
          source: { type: "string", enum: ["manual", "approval", "agent"] },
          assignee: { type: "string" },
          createdAt: { type: "string" },
          actionId: { type: "string" },
        },
      },
    },
  },
};

const TASK_BOARD_INITIAL_STATE: AgentTaskBoardState = { tasks: [] };

const sortTasks = (tasks: AgentTaskBoardTask[]) =>
  [...tasks].sort((left, right) => {
    if (left.done !== right.done) return left.done ? 1 : -1;
    return new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime();
  });

const areTasksEqual = (left: AgentTaskBoardTask, right: AgentTaskBoardTask) =>
  left.id === right.id &&
  left.title === right.title &&
  left.description === right.description &&
  left.done === right.done &&
  left.source === right.source &&
  left.assignee === right.assignee &&
  left.createdAt === right.createdAt &&
  left.actionId === right.actionId;

const normalizeExternalTask = (
  task: AgentTaskBoardExternalTask,
  existing?: AgentTaskBoardTask,
): AgentTaskBoardTask => ({
  id: task.id,
  title: task.title,
  description: task.description,
  done: existing?.done ?? task.done ?? false,
  source: task.source,
  assignee: task.assignee,
  createdAt: task.createdAt,
  actionId: task.actionId,
});

const AgentTaskBoard: React.FC<AgentTaskBoardProps> = ({
  interactableId,
  externalTasks = [],
}) => {
  const registeredId = useAssistantInteractable("taskBoard", {
    id: interactableId,
    description:
      "A persistent owner task board for manual follow-ups, employee tasks, and approval work generated by the agent workspace.",
    stateSchema: TASK_BOARD_STATE_SCHEMA,
    initialState: TASK_BOARD_INITIAL_STATE,
  });

  const [state, { setState, setSelected, isPending, error }] =
    useInteractableState<AgentTaskBoardState>(registeredId, TASK_BOARD_INITIAL_STATE);

  useEffect(() => {
    if (externalTasks.length === 0) return;

    setState((prev: AgentTaskBoardState) => {
      const existingTasks = prev.tasks || [];
      const taskMap = new Map<string, AgentTaskBoardTask>(
        existingTasks.map((task) => [task.id, task]),
      );
      let changed = false;

      externalTasks.forEach((task) => {
        const current = taskMap.get(task.id);
        const next = normalizeExternalTask(task, current);
        if (!current || !areTasksEqual(current, next)) {
          taskMap.set(next.id, next);
          changed = true;
        }
      });

      if (!changed) return prev;

      const nextTasks = sortTasks(Array.from(taskMap.values()));
      if (
        nextTasks.length === existingTasks.length &&
        nextTasks.every((task, index) => areTasksEqual(task, existingTasks[index]!))
      ) {
        return prev;
      }

      return { tasks: nextTasks };
    });
  }, [externalTasks, setState]);

  const tasks = useMemo(() => sortTasks(state.tasks || []), [state.tasks]);
  const doneCount = tasks.filter((task) => task.done).length;

  const handleToggleTask = useCallback(
    (taskId: string) => {
      setSelected(true);
      setState((prev: AgentTaskBoardState) => ({
        tasks: sortTasks(
          (prev.tasks || []).map((task: AgentTaskBoardTask) =>
            task.id === taskId ? { ...task, done: !task.done } : task,
          ),
        ),
      }));
    },
    [setSelected, setState],
  );

  return (
    <div
      onClick={() => setSelected(true)}
      className="w-full h-full flex flex-col overflow-hidden border-l border-border bg-background/[0.02] min-h-[320px] md:min-h-0"
    >
      {/* Header */}
      <div className="flex items-center gap-2 px-3 py-2 border-b border-border">
        <div className="flex items-center gap-2 flex-1 min-w-0">
          <ClipboardList className="h-4 w-4 text-muted-foreground flex-shrink-0" />
          <p className="text-sm font-semibold">Task Board</p>
        </div>

        {isPending && (
          <span className="inline-block h-3 w-3 animate-spin rounded-full border-2 border-border border-t-primary" />
        )}

        {tasks.length > 0 && (
          <span className="ml-auto rounded-full px-2 py-0.5 text-xs font-semibold text-primary bg-primary/10">
            {doneCount}/{tasks.length}
          </span>
        )}
      </div>

      {/* Body */}
      <div className="flex-1 min-h-0 overflow-y-auto">
        {Boolean(error) && (
          <div className="mx-3 mt-3 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-400">
            Failed to sync task board state.
          </div>
        )}

        {tasks.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full min-h-[200px] gap-1.5 text-center px-6">
            <ClipboardList className="h-8 w-8 text-muted-foreground/30 mb-1" />
            <p className="text-sm font-medium text-muted-foreground">No tasks yet.</p>
            <p className="text-xs text-muted-foreground/70">Ask the assistant to add some!</p>
          </div>
        ) : (
          <ul className="m-0 p-0 list-none">
            {tasks.map((task) => (
              <li key={task.id}>
                <button
                  type="button"
                  onClick={() => handleToggleTask(task.id)}
                  title={task.description || task.title}
                  className={cn(
                    "flex w-full items-center gap-3 rounded-none px-3 py-0 min-h-9 text-left transition-opacity hover:bg-muted/50",
                    task.done && "opacity-50",
                  )}
                >
                  {task.done ? (
                    <CheckCircle2 className="h-4 w-4 text-primary flex-shrink-0" />
                  ) : (
                    <Circle className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                  )}
                  <span
                    className={cn(
                      "flex-1 min-w-0 text-sm font-medium break-words",
                      task.done ? "text-muted-foreground line-through" : "text-foreground",
                    )}
                  >
                    {task.title}
                  </span>
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
};

export default AgentTaskBoard;
